name: "build"
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: "[17.4,17.5)"

      - name: Build app for release
        run: msbuild -restore -p:Configuration=Release -p:OutputPath=D:\a\BF1ServerTools\output\BF1ServerTools BF1ServerTools.sln

      - name: Compress output
        run: Compress-Archive -Path D:\a\BF1ServerTools\output\BF1ServerTools -DestinationPath D:\a\BF1ServerTools\output\BF1ServerTools.zip

      - name: Upload firmware to WeTransfer
        id: wetransfer
        run: |
          Start-BitsTransfer -Source https://github.com/Mikubill/transfer/releases/download/v0.4.17/transfer_0.4.17_windows_amd64.zip -Destination D:\a\BF1ServerTools
          Expand-Archive -Path D:\a\BF1ServerTools\transfer_0.4.17_windows_amd64.zip -DestinationPath D:\a\BF1ServerTools
          ./transfer.exe wet -s --no-progress D:\a\BF1ServerTools\output\BF1ServerTools.zip

      - name: Upload bin directory
        uses: actions/upload-artifact@main
        with:
          name: BF1ServerTools
          path: D:\a\BF1ServerTools\output
