name: "build"
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: "[17.4,17.5)"

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.11

      - name: Install dependencies
        run: dotnet restore

      - name: Build app for release
        run: msbuild BF1ServerTools.sln

      - name: show differences
        run: |
          Get-Location
          git diff
          get-item .
